language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
<<<<<<< HEAD
  - docker-compose run recipeproject_web sh -c "python manage.py test && flake8"
